---
# tasks file for arc-install-wordpress
- name: Check if wordpress is already installed
  stat:
    path: "{{ wordpress_web_dir }}"
  register: wordpress_dir
  tags:
  - wordpress

- name: Install necessary additional PHP packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php-curl
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-xml
    - php-xmlrpc

- name: Enable .htaccess overrides in apache2.conf file
  blockinfile:
    path: "/etc/apache2/apache2.conf"
    block: |
      <Directory /var/www/html/>
          AllowOverride All
      </Directory>

- name: Enable the mod_rewrite module
  command: a2enmod rewrite

- name: Download the latest WordPress archive
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Un-archive the WordPress archive
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: "True"

- name: Create dummy .htaccess file
  file:
    path: /tmp/wordpress/.htaccess
    state: touch
    mode: 660

- name: Copy dummy WordPress configuration file to proper one
  copy:
    src: /tmp/wordpress/wp-config-sample.php
    dest: /tmp/wordpress/wp-config.php
    remote_src: "True"

- name: Create an upgrade direcrory for WordPress
  file:
    path: /tmp/wordpress/wp-content/upgrade
    state: directory

- name: Copy WordPress files to web document root
  command: creates="{{ wordpress_web_dir }}" mv "/tmp/wordpress" "{{ wordpress_web_dir }}"

- name: Change ownership on all web documents
  file:
    path: "{{ web_document_root }}"
    state: directory
    recurse: yes
    owner: ubuntu
    group: www-data
    mode: "g+s"

- name: Give group write access to the wp-content directory
  file:
    path: "{{ wordpress_web_dir }}/wp-content"
    state: directory
    mode: "g+w"

- name: Give group write access to themes/plugins folders
  file:
    path: "{{ item }}"
    state: directory
    mode: "g+w"
    recurse: yes
  with_items:
    - "{{ wordpress_web_dir }}/wp-content/themes"
    - "{{ wordpress_web_dir }}/wp-content/plugins"
