---
# tasks file for arc-install-wordpress
- name: Check if wordpress is already installed
  stat:
    path: "{{ wordpress_web_dir }}"
  register: wordpress_dir
  tags:
  - wordpress

- name: Install necessary additional PHP packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php-curl
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-xml
    - php-xmlrpc
  tags:
  - wordpress

- name: Enable .htaccess overrides in apache2.conf file
  blockinfile:
    path: "/etc/apache2/apache2.conf"
    block: |
      <Directory /var/www/html/>
          AllowOverride All
      </Directory>
  tags:
  - wordpress

- name: Enable the mod_rewrite module
  command: a2enmod rewrite
  tags:
  - wordpress

- name: Download the latest WordPress archive
  get_url:
    url: "{{ wordpress_url }}"
    dest: "/tmp/{{ wordpress_archv }}"
  when: wordpress_dir.stat.exists == False
  tags:
  - wordpress

- name: Un-archive the WordPress archive
  unarchive:
    src: "/tmp/{{ wordpress_archv }}"
    dest: /tmp
    remote_src: "True"
  tags:
  - wordpress

- name: Check if wordpress tmp directory exists
  stat:
    path: "{{ wordpress_tmp_dir }}"
  register: wordpress_temp_dir
  tags:
  - wordpress

- name: Create dummy .htaccess file
  file:
    path: "{{ wordpress_tmp_dir }}/.htaccess"
    state: "touch"
    mode: 660
  when: wordpress_temp_dir.stat.exists == True
  tags:
  - wordpress

- name: Copy dummy WordPress configuration file to proper one
  copy:
    src: "{{ wordpress_tmp_dir }}/wp-config-sample.php"
    dest: "{{ wordpress_tmp_dir }}/wp-config.php"
    remote_src: "True"
  when: wordpress_temp_dir.stat.exists == True
  tags:
  - wordpress

- name: Create an upgrade direcrory for WordPress
  file:
    path: "{{ wordpress_tmp_dir }}/wp-content/upgrade"
    state: "directory"
  when: wordpress_temp_dir.stat.exists == True
  tags:
  - wordpress

- name: Copy WordPress files to web document root
  command: creates="{{ wordpress_web_dir }}" mv "{{ wordpress_tmp_dir }}" "{{ wordpress_web_dir }}" #"
  when: wordpress_temp_dir.stat.exists == True
  tags:
  - wordpress

- name: Change ownership on all web documents
  file:
    path: "{{ web_document_root }}"
    state: "directory"
    recurse: "yes"
    owner: "ubuntu"
    group: "www-data"
    mode: "g+sw,a+r"
  tags:
  - wordpress

# name: Give group write access to the wp-content directory
# file:
#   path: "{{ wordpress_web_dir }}/wp-content"
#   state: "directory"
#   mode: "g+w"
# tags:
# - wordpress
#
# name: Give group write access to themes/plugins folders
# file:
#   path: "{{ item }}"
#   state: "directory"
#   mode: "g+w"
#   recurse: "yes"
# with_items:
#   - "{{ wordpress_web_dir }}/wp-content/themes"
#   - "{{ wordpress_web_dir }}/wp-content/plugins"
# tags:
# - wordpress

- name: Writes wp-config.php file wth valid data
  template:
    src: "{{ wordpress_config_template }}"
    dest: "{{ wordpress_web_dir }}/wp-config.php"
    force: "yes"
  tags:
  - wordpress
